### PR TITLE
Add the CPay SDK JAR as a library dep in Sample App

### PR DESCRIPTION
**Pull request by devinmorgan**
## What
The CPay SDK is a JAR file that the POS terminal manufacturers created. Forage needs to use the facilities the CPay SDK offers to interact with the hardware on the terminal such as the printer, magstripe reader, etc

## Why
Split this up into its own PR because it's a pre-req for all subsequent POS hardware work. I also wanted to make sure the that Github action workflows would play nicely with this.

## Test Plan

- ❌ I've added unit tests for this change.  No unit tests because this updates the build configuration no business logic
- ❌ The reviewer should manually test the changes in this PR.  It is sufficient to see that the CI job passes.

## How
Should be rolled out as soon as it is approved.

### CODE REVIEW

**Comment by devinmorgan** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #147** <a href="https://app.graphite.dev/github/pr/teamforage/forage-android-sdk/147?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/teamforage/forage-android-sdk/147?utm_source=stack-comment).

**Review by djoksimo — CHANGES_REQUESTED** [review]
Looks like there's a linting error?

**Comment by devinmorgan** [comment]
> Looks like there's a linting error?

Ahh interesting. Just re-ran the job and it appears to work 🙏

**Review by djoksimo — APPROVED** [review]
Nice stuff @devinmorgan ! Cool to see this and your receipt printer implementation #148  in the Android repo @devinmorgan !

**Pull request merged**
